language: node_js

branches:
  only:
  - master

node_js:
  - "stable"

cache:
  directories:
  - node_modules

script:
  - npm run build

before_deploy:
  - zip ${TRAVIS_TAG}.zip build

deploy:
  provider: releases
  api_key: "629ca4b3311aaf44ba0cfecfee3c40c91e782f67"
  file: ${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true